import type { Metadata } from "next";
import { Epilogue } from "next/font/google";
import "./globals.css";

const font = Epilogue({
  subsets: ["vietnamese", "latin"],
  weight: ["500", "700", "600", "400"],
});

export const metadata: Metadata = {
  title: "Sunfil",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="vi">
      <body
        className={`${font.className} antialiased text-[#1C252E] bg-[#F4F6F8]`}
      >
        {children}
      </body>
    </html>
  );
}
