import type { Metadata } from "next";
import { Epilogue } from "next/font/google";
import "./globals.css";

const font = Epilogue({
  subsets: ["vietnamese", "latin"],
  weight: ["500", "700", "600"],
});

export const metadata: Metadata = {
  title: "Sunfil",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${font.className} antialiased`}>{children}</body>
    </html>
  );
}
